apiVersion: v1
kind: ConfigMap
metadata:
  name: development-index-html-configmap
  namespace: development
data: 
  contentHTML: {{ .values-dev.data.contentHTML }}

---
apiVersion: v1
kind: Secret
metadata:
  name: production-index-html-configmap
  namespace: production
data: 
  contentHTML: {{ .values-dev.data.contentHTML }}
